/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace policy {
    export interface PoliciesService {
        getById(
            data: PolicyById,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Policy>;
        getAll(
            data: Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<PolicyList>;
        create(
            data: Policy,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Policy>;
        update(
            data: Policy,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Policy>;
        remove(
            data: PolicyById,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Empty>;
    }
    export interface PolicyById {
        id?: number;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
    export interface PolicyList {
        policies?: policy.Policy[];
    }
    export interface Policy {
        policyId?: number;
        policyName?: string;
    }
}

